# Generated by Django 5.2.6 on 2025-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("availability", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityrule",
            name="event_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all event types",
                related_name="availability_rules",
                to="events.eventtype",
            ),
        ),
    ]
