# Generated by Django 5.2.6 on 2025-09-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("availability", "0002_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityrule",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blockedtime",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_times",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buffertime",
            name="organizer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buffer_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dateoverriderule",
            name="event_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all event types",
                related_name="date_overrides",
                to="events.eventtype",
            ),
        ),
        migrations.AddField(
            model_name="dateoverriderule",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recurringblockedtime",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_blocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availabilityrule",
            unique_together={("organizer", "day_of_week", "start_time", "end_time")},
        ),
        migrations.AddIndex(
            model_name="blockedtime",
            index=models.Index(
                fields=["organizer", "source", "external_id"],
                name="blocked_tim_organiz_2d7a07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blockedtime",
            index=models.Index(
                fields=["organizer", "start_datetime", "end_datetime"],
                name="blocked_tim_organiz_7f3b0b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dateoverriderule",
            unique_together={("organizer", "date")},
        ),
    ]
